# Generated by Django 3.0.5 on 2021-01-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='MyBlog', max_length=255),
        ),
    ]
